# Generated by Django 2.2.4 on 2019-08-27 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('img_url', models.CharField(max_length=90)),
                ('tier', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ChampionClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ChampionOrigin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheatsheet.Champion')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('img_url', models.CharField(max_length=90)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('img_url', models.CharField(max_length=90)),
                ('description', models.CharField(max_length=150)),
                ('members', models.ManyToManyField(through='cheatsheet.ChampionOrigin', to='cheatsheet.Champion')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('img_url', models.CharField(max_length=90)),
                ('description', models.CharField(max_length=150)),
                ('members', models.ManyToManyField(through='cheatsheet.ChampionClass', to='cheatsheet.Champion')),
            ],
        ),
        migrations.AddField(
            model_name='championorigin',
            name='corigin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheatsheet.Origin'),
        ),
        migrations.AddField(
            model_name='championclass',
            name='cclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheatsheet.Class'),
        ),
        migrations.AddField(
            model_name='championclass',
            name='champion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheatsheet.Champion'),
        ),
    ]
